[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "python github_agent_endpoint.py"
healthcheckPath = "/health"
healthcheckTimeout = 30
restartPolicyType = "always"
healthcheckInterval = 10 